Add main menu
Hivemind-Interactive/Nagzz-Community-Game pull request #13
Opened 2022-07-07 10:57 UTC by ZoazVA

2022-07-07 17:33 UTC, AWarmCupOfTea commented
Let's follow https://cbea.ms/git-commit/ for naming our PRs and commits.

2022-07-07 17:34 UTC, AWarmCupOfTea requested changes

2022-07-07 17:34 UTC, AWarmCupOfTea commented on scenes/Menu.gd
> +# Called every frame. 'delta' is the elapsed time since the previous frame.
Let's remove the unnecessary comments.

2022-07-07 17:36 UTC, ZoazVA commented on scenes/Menu.gd
> +# Called every frame. 'delta' is the elapsed time since the previous frame.
Ok I'll do it now

2022-07-07 19:08 UTC, AWarmCupOfTea commented
And please check the article I linked above. I would rename the commit to something like "Add main menu"

2022-07-08 21:34 UTC, AWarmCupOfTea requested changes

2022-07-08 21:34 UTC, AWarmCupOfTea commented on scenes/Menu.gd
> +func _ready():
Please add spacing between the functions like described in https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html

2022-07-09 00:14 UTC, AWarmCupOfTea approved these changes

2022-07-09 00:56 UTC, merged