added basic player health system
Hivemind-Interactive/Nagzz-Community-Game pull request #20
Opened 2022-07-14 06:37 UTC by TheMadHatter01

2022-07-14 09:44 UTC, AWarmCupOfTea requested changes

2022-07-14 09:44 UTC, AWarmCupOfTea commented on scenes/player/HealthStats.gd
> +extends Node
What's the difference between this file and HealthBar.gd ?

2022-07-14 09:44 UTC, AWarmCupOfTea commented on scenes/player/player.gd
> +func _on_Area2D_area_entered(area):
Should this really be in the player class?

2022-07-14 09:46 UTC, AWarmCupOfTea commented
Pleas use this convention to name commits: https://cbea.ms/git-commit/

For example, `Add basic player health system`

2022-07-14 10:19 UTC, TheMadHatter01 commented on scenes/player/HealthStats.gd
> +extends Node
the HealthBar.gd was to get the health bar to work

2022-07-14 10:23 UTC, TheMadHatter01 commented on scenes/player/player.gd
> +func _on_Area2D_area_entered(area):
There is probably a better way to do it, but thats how i know how to do it.

2022-07-14 10:42 UTC, AWarmCupOfTea commented on scenes/player/player.gd
> +func _on_Area2D_area_entered(area):
Well, any class should follow [Single-responsibility principle](https://en.wikipedia.org/wiki/Single-responsibility_principle), so the logic of this Area2D should be inside its class.

2022-07-14 10:43 UTC, AWarmCupOfTea commented on scenes/player/HealthStats.gd
> +extends Node
I see duplicate code in both files, and I don't understand why is it needed.

2022-07-14 10:54 UTC, TheMadHatter01 commented on scenes/player/HealthStats.gd
> +extends Node
ok, ill try cleaning up the code

2022-07-14 10:59 UTC, TheMadHatter01 commented on scenes/player/player.gd
> +func _on_Area2D_area_entered(area):
i see, so ill attach a script to the area2d with that bit of code?

2022-07-14 11:01 UTC, AWarmCupOfTea commented on scenes/player/player.gd
> +func _on_Area2D_area_entered(area):
Yes, you need to figure out how to keep the logic inside their relevant classes. It's a bad idea to pile everything in one place.

2022-07-15 02:51 UTC, TheMadHatter01 commented on scenes/player/player.gd
> +func _on_Area2D_area_entered(area):
Ok, I won't be able to work on it today or tomorrow, so I'll continue on Sunday

2022-07-18 11:24 UTC, closed without merging