add basic projectile
Hivemind-Interactive/Nagzz-Community-Game pull request #21
Opened 2022-07-14 15:14 UTC by przemo1232

2022-07-14 18:43 UTC, AWarmCupOfTea requested changes
Please format the code according to https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html

2022-07-14 19:41 UTC, AWarmCupOfTea requested changes

2022-07-14 20:51 UTC, przemo1232 commented on scenes/player/player.gd
> +	if PROJECTILE:
i don't think so, but it was written like that in a tutorial so i added it

2022-07-14 21:05 UTC, AWarmCupOfTea requested changes

2022-07-14 21:47 UTC, przemo1232 commented on scenes/player/player.gd
> +		last_attack_time = 0.0
from what i found you can't pass parameters to a scene and this was the other option

2022-07-14 22:30 UTC, AWarmCupOfTea commented on scenes/player/player.gd
> +		last_attack_time = 0.0
https://godotengine.org/qa/4786/how-to-pass-parameters-when-instantiating-a-node

2022-07-15 11:34 UTC, przemo1232 commented on scenes/player/player.gd
> +		last_attack_time = 0.0
moved the logic to the projectile scene and reformatted the code, hope it's good now

2022-07-15 15:29 UTC, AWarmCupOfTea approved these changes

2022-07-15 15:29 UTC, merged