basic player health system
Hivemind-Interactive/Nagzz-Community-Game pull request #23
Opened 2022-07-18 11:19 UTC by TheMadHatter01

2022-07-18 11:34 UTC, AWarmCupOfTea requested changes

2022-07-18 11:34 UTC, AWarmCupOfTea commented on scenes/player/HealthStats.gd
> +	print("hi")
Please remove this

2022-07-18 11:34 UTC, AWarmCupOfTea commented on scenes/player/HealthStats.gd
> +	max_health = max(1, new_max_health)
Please add a check that `new_max_health` is within valid range

2022-07-18 11:34 UTC, AWarmCupOfTea commented on scenes/player/HealthStats.gd
> +	health = clamp(health, 0, max_health)
Please add a check that `new_health` is within valid range

2022-07-19 04:26 UTC, TheMadHatter01 commented on scenes/player/HitBox.gd
> +onready var player_stats = HealthStats
what should i put instead?

2022-07-19 04:38 UTC, TheMadHatter01 commented on scenes/player/HealthStats.gd
> +	health = clamp(health, 0, max_health)
im confused by what you mean by this, doesn't the clamp keep it from going out of range?

2022-07-19 04:43 UTC, TheMadHatter01 commented on scenes/player/HealthStats.gd
> +	max_health = max(1, new_max_health)
what do you mean by valid range?

2022-07-19 14:38 UTC, echooff2 requested changes
And please change file names to match that of the rest of the project and that of [godot style guide](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html#file-names)

2022-07-19 14:38 UTC, echooff2 commented on scenes/player/HealthStats.gd
> +
```suggestion


```
https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html#blank-lines

2022-07-19 14:38 UTC, echooff2 commented on scenes/player/HealthStats.gd
> +
```suggestion


```
https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html#blank-lines

2022-07-19 14:38 UTC, echooff2 commented on scenes/player/HealthStats.gd
> +
```suggestion


```
https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html#blank-lines

2022-07-19 14:38 UTC, echooff2 commented on scenes/player/HitBox.gd
> +onready var player_stats = HealthStats
It is not needed, you can directly use HealthStats, without this

2022-07-19 14:38 UTC, echooff2 commented on scenes/player/HitBox.gd
> +
```suggestion


```
https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html#blank-lines

2022-07-19 18:41 UTC, AWarmCupOfTea commented on scenes/player/HealthStats.gd
> +	health = clamp(health, 0, max_health)
If there is an invalid value of `new_health` passed, clamp will just change it to the closest valid one, but we also need to be notified about a bug in the code somehow. You can add `assert` to check if the argument is within valid range:

`assert(health > 0 and health < max_health, "Invalid argument value for health")`

or

`assert(clamp(health, 0, max_health) == healh, "Invalid argument value for health")` if you want to be fancy :)

2022-07-19 18:41 UTC, AWarmCupOfTea commented on scenes/player/HealthStats.gd
> +	max_health = max(1, new_max_health)
See my answer below.

2022-07-19 18:48 UTC, AWarmCupOfTea commented on scenes/player/HitBox.gd
> +onready var player_stats = HealthStats
Either see echooff2 answer, or you can use Node methods to get the scene from the tree, like `get_parent("Player").find_node()` or something

2022-07-20 03:37 UTC, TheMadHatter01 commented on scenes/player/HealthStats.gd
> +	health = clamp(health, 0, max_health)
i see, thanks for the feedback

2022-07-20 14:31 UTC, echooff2 requested changes

2022-07-20 14:31 UTC, echooff2 commented on scenes/player/HealthBar.gd
> +
> Use one line feed character at the end of each file. (editor default)

https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html#encoding-and-special-characters

2022-07-20 14:31 UTC, echooff2 commented on scenes/player/HealthStats.gd
> +
> Use one line feed character at the end of each file. (editor default)

https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html#encoding-and-special-characters

2022-07-21 12:22 UTC, echooff2 commented
I just noticed that file names are named wrong, it should be snake_case. HealthBar.gd, HealthStats.gd, DamageTest.gd have 2 empty lines at the end ( can't be seen on github because github cuts last empty line out but I can see it in vscode ) and HitBox.gd has 3 empty lines, should be 1. There are tools to autoformat for you. If you use vscode you can use [this extension](https://marketplace.visualstudio.com/items?itemName=Razoric.gdscript-toolkit-formatter), if not you can use [this tool](https://github.com/Scony/godot-gdscript-toolkit), while these formatter are not perfect, they can still help with formatting code correctly. And you still haven't addressed the two warnings I wrote about in the first review.

2022-07-24 01:22 UTC, TheMadHatter01 commented
i just set it to ignore the 2 warnings about not using the value, is that ok? because im not sure how else to handle it

2022-07-24 18:01 UTC, echooff2 submitted a review, later dismissed

2022-07-30 13:59 UTC, AWarmCupOfTea approved these changes

2022-07-31 14:19 UTC, echooff2 requested changes

2022-07-31 14:19 UTC, echooff2 commented on scenes/player/health_bar.gd
> +	var max_HP_connect_err = HealthStats.connect("max_health_changed", self, "set_max_health_bar")
use snake_case for naming variables

2022-07-31 14:19 UTC, echooff2 commented on scenes/player/health_bar.gd
> +	var HP_connect_err = HealthStats.connect("health_changed", self, "set_health_bar")
use snake_case for naming variables

2022-07-31 14:19 UTC, echooff2 commented on scenes/player/player.tscn
>  [ext_resource path="res://scenes/player/weapon.gd" type="Script" id=9]
on first line load_step should be set to 17. load_step=count_of_ext_resource + count_of_sub_resource + 1. While it works when set incorrectly, it could affect loading bars when we make one. https://docs.godotengine.org/en/3.4/development/file_formats/tscn.html#file-structure

2022-08-01 06:40 UTC, TheMadHatter01 commented on scenes/player/player.tscn
>  [ext_resource path="res://scenes/player/weapon.gd" type="Script" id=9]
so just change the load step count from 15 to 17?

2022-08-01 17:30 UTC, echooff2 approved these changes

2022-08-03 09:21 UTC, merged