Add weapon reload
Hivemind-Interactive/Nagzz-Community-Game pull request #27
Opened 2022-07-22 20:58 UTC by AWarmCupOfTea

2022-07-24 18:57 UTC, echooff2 requested changes

2022-07-24 18:57 UTC, echooff2 commented on scenes/player/in_air.gd
> +	if Input.is_action_just_pressed("jump") and _coyote_time_elapsed <= _player.COYOTE_TIME_SECS:
what line length do we want to keep lines? [style guide](url) says it must be kept under 100 which it is kept, but also suggests that it's best to keep it under 80 ( for me personally when I have vscode on half of the screen it's best if code is under 85 ).

2022-07-24 18:57 UTC, echooff2 commented on scenes/weapons/base_weapon.gd
> +var ammo := 0.0
ammo probably should be int

2022-07-24 18:57 UTC, echooff2 commented on scenes/weapons/base_weapon.gd
> +		if ammo == 0:
I think this should be `ammo <= 0`, just in case it bugs or some other script changes it to negative value and probably ammo should be checked before _on_fire, so when player loses ammo through other script they won't be able to fire without reloading first

2022-07-24 22:46 UTC, AWarmCupOfTea commented on scenes/player/in_air.gd
> +	if Input.is_action_just_pressed("jump") and _coyote_time_elapsed <= _player.COYOTE_TIME_SECS:
I used [gdscript formatter](https://www.gdquest.com/tutorial/godot/gdscript/gdscript-formatter/) to format the code, and I think it's best if we stick with using it to format all out code. This was we can be sure that our code is always formatted consistently, and we won't need to format it manually.

2022-07-24 22:50 UTC, AWarmCupOfTea commented on scenes/weapons/base_weapon.gd
> +var ammo := 0.0
I used int initially, but then I thought what if we will have a modifier in future that affects ammo by percentage? If there are multiple of those, it's better to have it float.

2022-07-25 14:51 UTC, echooff2 commented on scenes/player/in_air.gd
> +	if Input.is_action_just_pressed("jump") and _coyote_time_elapsed <= _player.COYOTE_TIME_SECS:
this formatter  accepts argument `-l`  which tells formatter line length, but it requires specifying it everytime so I guess 100 it is. In my case since I use vscode with formatter extension ( uses same tool under the hood ) I have permament settings, I will revert it back to 100.

2022-07-25 15:00 UTC, echooff2 commented on scenes/weapons/base_weapon.gd
> +var ammo := 0.0
It still doesn't make sense to have 1,5 bullets. If we want modifiers we could round/floor/ceil whatever makes the most sense

2022-07-25 19:52 UTC, echooff2 approved these changes

2022-07-25 19:54 UTC, merged