Add weapon pickup scene
Hivemind-Interactive/Nagzz-Community-Game pull request #30
Opened 2022-08-01 21:22 UTC by AWarmCupOfTea

2022-08-02 11:45 UTC, echooff2 commented
From what I can see this makes it more restrictive in picking collision for interactable. The previous one allowed to pick a shape and size of it, and this one only allows scaling the whole npc, which might have more things in in the future. So not sure why changing it this way.

2022-08-02 16:10 UTC, AWarmCupOfTea commented
I don't think it's more restrictive, now you need to add your own collision shape to an interactable scene, so it should actually be even more flexible.

2022-08-02 16:39 UTC, echooff2 commented
While the interactable scene in itself is more flexible, the npc scene, room_switcher scene and weapon_pickup scene is less flexible because it only allows to resize the collision. And there might be problem if we add something to those scenes that shouldn't be scalled. I think it would be better if that scene(e.g. npc scene) had a CollisionShape2D or CollisionPolygon2D and passed it to the underlying interactable scene. So like

test_npc.tscn:
 - npc node
   - CollisionShape2D <- `that collision`
 - [...rest_of_nodes]

npc.tscn:
 - interactable node
 - [...rest_of_nodes]

and npc's script would move/duplicate `that collision` to npc.tscn's interactable node. And npc.gd would use `_get_configuration_warning` to display that that node has to have a collision node.

2022-08-02 19:56 UTC, echooff2 commented
user of interactable.tscn has more flexibility but user of scenes like npc.tscn has less flexibility

2022-08-02 20:29 UTC, AWarmCupOfTea commented
Ah, I see what you mean now. I think that since we don't actually have any code in NPC scene now, we can think about how to handle that later, perhaps just not use Interactable with NPC. What do you think?

2022-08-02 20:48 UTC, echooff2 commented
Yea, we could handle that later, I have an idea how to handle that ( which I wrote about earlier), so maybe I will do that after I complete tooltip popup and this is merged. And I wrote about npc as an example not that it is only about npc. I will review code later tonight or tomorrow.

2022-08-03 14:41 UTC, echooff2 requested changes

2022-08-03 14:41 UTC, echooff2 commented on scenes/interactable/interactable.gd
> +class_name Interactable
Do we really need this to be a global class?

2022-08-03 14:41 UTC, echooff2 commented on scenes/player/interaction_box.gd
> +	if area is Interactable:
Why changing that? Previous allowed other interactable to exists as long as it had interacted signal.

2022-08-03 14:41 UTC, echooff2 commented on scenes/weapon_pickup/weapon_pickup.gd
> +func _ready():
maybe add assert for weapon_scene and weapon_texture?

2022-08-03 14:41 UTC, echooff2 commented on scenes/weapon_pickup/weapon_pickup.gd
> +	var weapon = player.find_node("Weapon")
maybe find the weapon node in _ready because find_node is quite expensive 

> Note: As this method walks through all the descendants of the node, it is the slowest way to get a reference to another node. Whenever possible, consider using [get_node](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-get-node) instead. To avoid using [find_node](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-find-node) too often, consider caching the node reference into a variable. ~ https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-find-node

2022-08-03 14:41 UTC, echooff2 commented on scenes/weapon_pickup/weapon_pickup.gd
> +	if weapon.get_child_count() > 0:
maybe instead of not allowing picking up weapons when you already have a weapon, replace the weapon with new one

2022-08-04 17:34 UTC, AWarmCupOfTea commented on scenes/interactable/interactable.gd
> +class_name Interactable
Is there a reason not to? It just makes it easier to search for.

2022-08-04 17:35 UTC, AWarmCupOfTea commented on scenes/player/interaction_box.gd
> +	if area is Interactable:
Good point, I will revert it back. It just looked nicer in code.

2022-08-04 17:44 UTC, AWarmCupOfTea commented on scenes/weapon_pickup/weapon_pickup.gd
> +	var weapon = player.find_node("Weapon")
Good point. Maybe in future we would keep track of weapon pickups in some sort of a game director class, since it would populate them with weapons instead of having those hardcoded.

2022-08-04 17:46 UTC, AWarmCupOfTea commented on scenes/weapon_pickup/weapon_pickup.gd
> +	var weapon = player.find_node("Weapon")
I think it should be fine to just use `get_node` here.

2022-08-04 17:47 UTC, AWarmCupOfTea commented on scenes/weapon_pickup/weapon_pickup.gd
> +	if weapon.get_child_count() > 0:
I think the idea was that the gun is picked once before the run and can't be changed until death.

2022-08-04 18:11 UTC, echooff2 commented on scenes/weapon_pickup/weapon_pickup.gd
> +	if weapon.get_child_count() > 0:
Yes I know, but it could be done like in Hades, you can pick a weapon and swap it in hub world. And to prevent weapon swapping during run we can just not spawn any weapons there.

2022-08-04 18:55 UTC, AWarmCupOfTea commented on scenes/weapon_pickup/weapon_pickup.gd
> +	if weapon.get_child_count() > 0:
Fixed

2022-08-04 18:58 UTC, echooff2 commented on scenes/interactable/interactable.gd
> +class_name Interactable
I think the opposite. Imo it is easier to search for class definition file when the path is there. In both cases ctrl+left_click works(at least in vscode). And the global classes polluts global name space. And what if at some point there will be more Interactable classes? I think the bigger the game gets the more annoying global classes will be.

> The issue it brings is that every class must have a unique name across your entire application. This isn’t really a problem for high-level classes, such as a Player class, a SkeletonEnemy class, a Knight class, etc, but it can be a problem if you’re doing something like a state machine where each entity may have a state with the same name. All of the previous examples could have a MoveState class, for instance, but that is not allowed in the global state. You could give each state a unique name, such as PlayerMoveState, but really, that’s a situation where you shouldn’t need a global reference to the class anyways.
You also have to make sure not to use a class name that is already in use in Godot, such as “Sprite” or “Timer”. So just think about the implications of throwing a class into the global namespace before doing it. ~ https://shaggydev.com/2021/10/19/godot-class-name/

So I think we should reserve global classes only to classes that a lot of script might need like Player class

2022-08-04 19:02 UTC, AWarmCupOfTea commented on scenes/interactable/interactable.gd
> +class_name Interactable
Fixed

2022-08-04 19:17 UTC, echooff2 approved these changes

2022-08-04 19:38 UTC, merged