add pause menu
Hivemind-Interactive/Nagzz-Community-Game pull request #31
Opened 2022-08-03 10:00 UTC by TheMadHatter01

2022-08-03 14:54 UTC, echooff2 requested changes
This pr doesn't load in editor

2022-08-03 14:54 UTC, echooff2 commented on scenes/menu/Pause_Menu.gd
> +var is_paused = false setget set_is_paused
use `:=` instead of `=` here. I feel like this would be better if you did like function to toggle/pause/unpause and change this var to private, instead of setget way

2022-08-04 01:33 UTC, TheMadHatter01 commented on scenes/menu/Pause_Menu.gd
> +var is_paused = false setget set_is_paused
ok ill make a function for it instead, also whats the difference between using := and =?

2022-08-04 15:57 UTC, echooff2 commented on scenes/menu/Pause_Menu.gd
> +var is_paused = false setget set_is_paused
https://docs.godotengine.org/en/3.1/getting_started/scripting/gdscript/static_typing.html#how-to-use-static-typing

2022-08-04 16:17 UTC, echooff2 requested changes
Still doesn't work `loading failed due to missing dependencies: res://scenes/menu/gui.tscn` it's probably linux only problem because linux cares about case-sensitivity and windows doesn't. If you rename GUI.tscn to gui.tscn it probably should be fixed. And Pause_Menu.* should be pause_menu.*. Please use gdformat before commiting.

2022-08-04 16:17 UTC, echooff2 commented on scenes/menu/Pause_Menu.gd
> +	toggle_pause()
would be better if this called unpause() instead

2022-08-04 16:17 UTC, echooff2 commented on scenes/menu/Pause_Menu.gd
> +	toggle_pause()
would be better if this called pause()

2022-08-04 22:58 UTC, TheMadHatter01 commented on scenes/menu/Pause_Menu.gd
> +	toggle_pause()
Ok

2022-08-04 23:00 UTC, TheMadHatter01 commented on scenes/menu/Pause_Menu.gd
> +	toggle_pause()
Thats just the name of the button, but I can do that

2022-08-04 23:04 UTC, TheMadHatter01 commented
> Still doesn't work `loading failed due to missing dependencies: res://scenes/menu/gui.tscn` it's probably linux only problem because linux cares about case-sensitivity and windows doesn't. If you rename GUI.tscn to gui.tscn it probably should be fixed. And Pause_Menu.* should be pause_menu.*. Please use gdformat before commiting.

On my local repository it's named properly, I don't know why it hasn't changed here, maybe I'll rename it again and commit it to see if that fixes it

2022-08-04 23:06 UTC, TheMadHatter01 commented on scenes/menu/Pause_Menu.gd
> +var is_paused = false setget set_is_paused
Ah I see, thanks

2022-08-05 12:56 UTC, echooff2 commented on scenes/menu/Pause_Menu.gd
> +	toggle_pause()
no, I meant instead of toggle_pause

2022-08-10 03:35 UTC, TheMadHatter01 commented on scenes/menu/Pause_Menu.gd
> +	toggle_pause()
isn't toggle pause better because i use one function for both pause and unpause?

2022-08-12 16:30 UTC, echooff2 commented on scenes/menu/Pause_Menu.gd
> +	toggle_pause()
The code will be more straight forward with unpause. When you read code you will see that resume button toggle the pause, but logically speaking it should unpause. I think with unpause here code will better self document itself. And there should be pause, unpause and toggle public methods so other scripts could pause/unpause.

2022-08-13 09:48 UTC, TheMadHatter01 commented on scenes/menu/Pause_Menu.gd
> +	toggle_pause()
Ah I see

2022-08-15 12:36 UTC, echooff2 commented
> On my local repository it's named properly, I don't know why it hasn't changed here, maybe I'll rename it again and commit it to see if that fixes it

Maybe try changing filenames through github. You can change file names in github by going into `Files changed` tab and clicking three dots on the right and choosing edit file. There you can change filename. Change GUI.tscn -> gui.tscn, Pause_Menu.tscn -> pause_menu.tscn and Pause_Menu.gd -> pause_menu.gd

2022-08-16 08:27 UTC, TheMadHatter01 commented
> > On my local repository it's named properly, I don't know why it hasn't changed here, maybe I'll rename it again and commit it to see if that fixes it
> 
> Maybe try changing filenames through github. You can change file names in github by going into `Files changed` tab and clicking three dots on the right and choosing edit file. There you can change filename. Change GUI.tscn -> gui.tscn, Pause_Menu.tscn -> pause_menu.tscn and Pause_Menu.gd -> pause_menu.gd

oh i didnt know that, i just changed it and it worked, thanks for the tip

2022-08-16 13:44 UTC, AWarmCupOfTea approved these changes

2022-08-22 17:38 UTC, echooff2 approved these changes

2022-08-23 04:48 UTC, merged