add a player dash
Hivemind-Interactive/Nagzz-Community-Game pull request #38
Opened 2022-08-23 04:50 UTC by TheMadHatter01

2022-08-23 18:14 UTC, AWarmCupOfTea requested changes

2022-08-23 18:14 UTC, AWarmCupOfTea commented on scenes/player/base_state.gd
> +		_state_machine.get_current_state()._update(delta)
I would suggest to make use of `_enter` function in Dash. Similar to how it is done in Jump.

2022-08-23 18:14 UTC, AWarmCupOfTea commented on scenes/player/dash.gd
> +func enter():
The parent function starts with an underscore, same for exit.

2022-08-23 18:14 UTC, AWarmCupOfTea commented on scenes/player/dash.gd
> +	if Input.is_action_just_pressed("dash") and !is_dashing() and _player.can_dash == true:
I think if the player is already in the Dash state, then dash was already pressed anyway.

2022-08-23 18:14 UTC, AWarmCupOfTea commented on scenes/player/dash.gd
> +func start_dash(duration):
Please add `: float` type hint.

2022-08-23 18:14 UTC, AWarmCupOfTea commented on scenes/player/player.gd
> +onready var dash = $StateMachine/BaseState/Dash
Is this needed? I don't think it is used.

2022-08-25 04:46 UTC, TheMadHatter01 commented on scenes/player/dash.gd
> +	if Input.is_action_just_pressed("dash") and !is_dashing() and _player.can_dash == true:
yah, I didn't realize that I could use the _enter func, for some reason i thought that was for something else😂

2022-08-25 18:11 UTC, AWarmCupOfTea approved these changes

2022-09-11 16:50 UTC, AWarmCupOfTea approved these changes

2022-09-11 16:50 UTC, merged